use glam::Vec2;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum GameObjectType {
	Solid = 0,
	Hazard = 2,
	Sawblade = 45,
	InverseGravityPortal = 3,
	NormalGravityPortal = 4,
	ShipPortal = 5,
	CubePortal = 6,
	Decoration = 7,
	YellowJumpPad = 8,
	PinkJumpPad = 9,
	GravityPad = 10,
	YellowJumpRing = 11,
	PinkJumpRing = 12,
	GravityRing = 13,
	InverseMirrorPortal = 14,
	NormalMirrorPortal = 15,
	BallPortal = 16,
	RegularSizePortal = 17,
	MiniSizePortal = 18,
	UfoPortal = 19,
	Modifier = 20,
	Breakable = 21,
	SecretCoin = 22,
	DualPortal = 23,
	SoloPortal = 24,
	Slope = 25,
	WavePortal = 26,
	RobotPortal = 27,
	TeleportPortal = 28,
	GreenRing = 29,
	Collectible = 30,
	UserCoin = 31,
	DropRing = 32,
	SpiderPortal = 33,
	RedJumpPad = 34,
	RedJumpRing = 35,
	CustomRing = 36,
	DashRing = 37,
	GravityDashRing = 38,
	CollisionObject = 39,
	Special = 40,
	SwingPortal = 41,
	GravityTogglePortal = 42,
	SpiderOrb = 43,
	SpiderPad = 44,
	TeleportOrb = 46,
	AnimatedHazard = 47,
	Unknown = -1,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum HitboxShape {
	Rectangle,
	Circle,
}

#[derive(Debug, Clone)]
pub struct GameObject {
	pub id: i32,
	pub object_type: GameObjectType,
	pub position: Vec2,
	pub rotation: f32,
	pub scale: Vec2,
	pub flip_x: bool,
	pub flip_y: bool,
	pub hitbox_shape: HitboxShape,
	pub width: f32,
	pub height: f32,
	pub obb: Option<super::obb::OBB2D>,
}
